title: Un alien en Sudamérica
author: alien
email: secularcode@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sudamérica sorprende a cualquiera. Aquí rigen otros códigos sociales, laborales, religiosos y morales.
  La primera impresión está muy alejada de la realidad.
  Hay que rascar bastante profundo para ver lo que es la realidad.
  Después de unos años viviendo aquí creo que puedo ofrecer una visión realista de lo que es la realidad en latinoamérica

# social links
twitter_username: YoAmo19 # DO NOT include the @ character, or else the build will fail!
github_username:  YoAmo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
